<template>
  <h1>Cards</h1>
  <pre>{{ result }}</pre>
</template>

<script setup>
const cards = ref([
  {
    card: "Iono",
    rarity: "Special Illustration Rare",
    number: "269",
    price: 130.11,
  },
  {
    card: "Magikarp",
    rarity: "Illustration Rare",
    number: "203",
    price: 74.72,
  },
  {
    card: "Iono",
    rarity: "Ultra Rare",
    number: "254",
    price: 49.1,
  },
  {
    card: "Chien-Pao ex",
    rarity: "Special Illustration Rare",
    number: "261",
    price: 34.55,
  },
  {
    card: "Tyranitar",
    rarity: "Illustration Rare",
    number: "222",
    price: 30.25,
  },
  {
    card: "Dendra",
    rarity: "Special Illustration Rare",
    number: "266",
    price: 24.06,
  },
  {
    card: "Raichu",
    rarity: "Illustration Rare",
    number: "211",
    price: 22.04,
  },
  {
    card: "Grusha",
    rarity: "Special Illustration Rare",
    number: "268",
    price: 20.79,
  },
  {
    card: "Chi-Yu ex",
    rarity: "Special Illustration Rare",
    number: "259",
    price: 20.07,
  },
  {
    card: "Meowscarada ex",
    rarity: "Special Illustration Rare",
    number: "256",
    price: 18.22,
  },
  {
    card: "Boss's Orders",
    rarity: "Special Illustration Rare",
    number: "265",
    price: 18.1,
  },
  {
    card: "Tinkaton ex",
    rarity: "Special Illustration Rare",
    number: "262",
    price: 17.81,
  },
  {
    card: "Skeledirge ex",
    rarity: "Special Illustration Rare",
    number: "258",
    price: 16.98,
  },
  {
    card: "Chien-Pao ex",
    rarity: "Hyper Rare",
    number: "274",
    price: 15.88,
  },
  {
    card: "Super Rod",
    rarity: "Hyper Rare",
    number: "276",
    price: 14.9,
  },
  {
    card: "Chien-Pao ex",
    rarity: "Ultra Rare",
    number: "236",
    price: 14.22,
  },
  {
    card: "Ting-Lu ex",
    rarity: "Special Illustration Rare",
    number: "263",
    price: 14.21,
  },
  {
    card: "Squawkabilly ex",
    rarity: "Special Illustration Rare",
    number: "264",
    price: 13.12,
  },
  {
    card: "Baxcalibur",
    rarity: "Illustration Rare",
    number: "210",
    price: 12.74,
  },
  {
    card: "Wo-Chien ex",
    rarity: "Special Illustration Rare",
    number: "257",
    price: 12.6,
  },
  {
    card: "Basic Water Energy",
    rarity: "Hyper Rare",
    number: "279",
    price: 11.48,
  },
  {
    card: "Frigibax",
    rarity: "Illustration Rare",
    number: "208",
    price: 10.54,
  },
  {
    card: "Maushold",
    rarity: "Illustration Rare",
    number: "226",
    price: 9.9,
  },
  {
    card: "Superior Energy Retrieval",
    rarity: "Hyper Rare",
    number: "277",
    price: 9.66,
  },
  {
    card: "Fuecoco",
    rarity: "Illustration Rare",
    number: "201",
    price: 9.65,
  },
  {
    card: "Chien-Pao ex",
    rarity: "Double Rare",
    number: "061",
    price: 9.13,
  },
  {
    card: "Quaquaval ex",
    rarity: "Special Illustration Rare",
    number: "260",
    price: 9.04,
  },
  {
    card: "Sprigatito",
    rarity: "Illustration Rare",
    number: "196",
    price: 9.01,
  },
  {
    card: "Meowscarada ex",
    rarity: "Hyper Rare",
    number: "271",
    price: 7.91,
  },
  {
    card: "Heracross",
    rarity: "Illustration Rare",
    number: "194",
    price: 7.51,
  },
  {
    card: "Boss's Orders",
    rarity: "Ultra Rare",
    number: "248",
    price: 7.5,
  },
  {
    card: "Mismagius",
    rarity: "Illustration Rare",
    number: "212",
    price: 6.78,
  },
  {
    card: "Tinkaton ex",
    rarity: "Ultra Rare",
    number: "240",
    price: 6.78,
  },
  {
    card: "Skeledirge ex",
    rarity: "Hyper Rare",
    number: "272",
    price: 6.76,
  },
  {
    card: "Saguaro",
    rarity: "Special Illustration Rare",
    number: "270",
    price: 6.69,
  },
  {
    card: "Giacomo",
    rarity: "Special Illustration Rare",
    number: "267",
    price: 6.4,
  },
  {
    card: "Dendra",
    rarity: "Ultra Rare",
    number: "250",
    price: 6.21,
  },
  {
    card: "Tinkatuff",
    rarity: "Illustration Rare",
    number: "217",
    price: 5.89,
  },
  {
    card: "Slowking ex",
    rarity: "Ultra Rare",
    number: "238",
    price: 5.82,
  },
  {
    card: "Marill",
    rarity: "Illustration Rare",
    number: "204",
    price: 5.8,
  },
  {
    card: "Paldean Tauros",
    rarity: "Illustration Rare",
    number: "218",
    price: 5.77,
  },
  {
    card: "Ting-Lu ex",
    rarity: "Hyper Rare",
    number: "275",
    price: 5.69,
  },
  {
    card: "Basic Grass Energy",
    rarity: "Hyper Rare",
    number: "278",
    price: 5.57,
  },
  {
    card: "Grusha",
    rarity: "Ultra Rare",
    number: "253",
    price: 5.55,
  },
  {
    card: "Sudowoodo",
    rarity: "Illustration Rare",
    number: "219",
    price: 5.28,
  },
  {
    card: "Quaquaval ex",
    rarity: "Hyper Rare",
    number: "273",
    price: 5.06,
  },
  {
    card: "Crocalor",
    rarity: "Illustration Rare",
    number: "202",
    price: 4.96,
  },
  {
    card: "Dedenne ex",
    rarity: "Ultra Rare",
    number: "239",
    price: 4.77,
  },
  {
    card: "Squawkabilly ex",
    rarity: "Ultra Rare",
    number: "247",
    price: 4.68,
  },
  {
    card: "Floragato",
    rarity: "Illustration Rare",
    number: "197",
    price: 4.65,
  },
  {
    card: "Eiscue",
    rarity: "Illustration Rare",
    number: "205",
    price: 4.53,
  },
  {
    card: "Tinkatink",
    rarity: "Illustration Rare",
    number: "216",
    price: 4.41,
  },
  {
    card: "Flamigo",
    rarity: "Illustration Rare",
    number: "227",
    price: 4.34,
  },
  {
    card: "Ting-Lu ex",
    rarity: "Ultra Rare",
    number: "243",
    price: 4.28,
  },
  {
    card: "Forretress ex",
    rarity: "Ultra Rare",
    number: "230",
    price: 4.26,
  },
  {
    card: "Meowscarada ex",
    rarity: "Ultra Rare",
    number: "231",
    price: 4.26,
  },
  {
    card: "Farigiraf",
    rarity: "Illustration Rare",
    number: "228",
    price: 4.13,
  },
  {
    card: "Orthworm",
    rarity: "Illustration Rare",
    number: "224",
    price: 3.68,
  },
  {
    card: "Quaxly",
    rarity: "Illustration Rare",
    number: "206",
    price: 3.55,
  },
  {
    card: "Paldean Wooper",
    rarity: "Illustration Rare",
    number: "221",
    price: 3.48,
  },
  {
    card: "Arctibax",
    rarity: "Illustration Rare",
    number: "209",
    price: 3.47,
  },
  {
    card: "Tropius",
    rarity: "Illustration Rare",
    number: "195",
    price: 3.42,
  },
  {
    card: "Bramblin",
    rarity: "Illustration Rare",
    number: "198",
    price: 3.36,
  },
  {
    card: "Dudunsparce",
    rarity: "Illustration Rare",
    number: "229",
    price: 3.33,
  },
  {
    card: "Annihilape ex",
    rarity: "Ultra Rare",
    number: "242",
    price: 3.24,
  },
  {
    card: "Fletchinder",
    rarity: "Illustration Rare",
    number: "199",
    price: 3.21,
  },
  {
    card: "Grafaiai",
    rarity: "Illustration Rare",
    number: "223",
    price: 3.21,
  },
  {
    card: "Skeledirge ex",
    rarity: "Ultra Rare",
    number: "233",
    price: 2.98,
  },
  {
    card: "Sandygast",
    rarity: "Illustration Rare",
    number: "214",
    price: 2.9,
  },
  {
    card: "Chi-Yu ex",
    rarity: "Ultra Rare",
    number: "234",
    price: 2.78,
  },
  {
    card: "Rookidee",
    rarity: "Illustration Rare",
    number: "225",
    price: 2.78,
  },
  {
    card: "Paldean Clodsire ex",
    rarity: "Ultra Rare",
    number: "244",
    price: 2.75,
  },
  {
    card: "Pyroar",
    rarity: "Illustration Rare",
    number: "200",
    price: 2.75,
  },
  {
    card: "Squawkabilly ex",
    rarity: "Double Rare",
    number: "169",
    price: 2.75,
  },
  {
    card: "Rabsca",
    rarity: "Illustration Rare",
    number: "215",
    price: 2.72,
  },
  {
    card: "Noivern ex",
    rarity: "Ultra Rare",
    number: "246",
    price: 2.67,
  },
  {
    card: "Quaxwell",
    rarity: "Illustration Rare",
    number: "207",
    price: 2.62,
  },
  {
    card: "Nacli",
    rarity: "Illustration Rare",
    number: "220",
    price: 2.44,
  },
  {
    card: "Bellibolt ex",
    rarity: "Ultra Rare",
    number: "237",
    price: 2.42,
  },
  {
    card: "Ting-Lu ex",
    rarity: "Double Rare",
    number: "127",
    price: 2.4,
  },
  {
    card: "Quaquaval ex",
    rarity: "Ultra Rare",
    number: "235",
    price: 2.32,
  },
  {
    card: "Gothorita",
    rarity: "Illustration Rare",
    number: "213",
    price: 2.21,
  },
  {
    card: "Wo-Chien ex",
    rarity: "Ultra Rare",
    number: "232",
    price: 2.13,
  },
  {
    card: "Meowscarada ex",
    rarity: "Double Rare",
    number: "015",
    price: 2.06,
  },
  {
    card: "Clavell",
    rarity: "Ultra Rare",
    number: "249",
    price: 1.89,
  },
  {
    card: "Lycanroc ex",
    rarity: "Ultra Rare",
    number: "241",
    price: 1.86,
  },
  {
    card: "Copperajah ex",
    rarity: "Ultra Rare",
    number: "245",
    price: 1.76,
  },
  {
    card: "Falkner",
    rarity: "Ultra Rare",
    number: "251",
    price: 1.73,
  },
  {
    card: "Saguaro",
    rarity: "Ultra Rare",
    number: "255",
    price: 1.71,
  },
  {
    card: "Giacomo",
    rarity: "Ultra Rare",
    number: "252",
    price: 1.65,
  },
  {
    card: "Iono",
    rarity: "Uncommon",
    number: "185",
    price: 1.58,
  },
  {
    card: "Forretress ex",
    rarity: "Double Rare",
    number: "005",
    price: 1.15,
  },
  {
    card: "Code Card - Paldea Evolved Pokemon Center Elite Trainer Box (Exclusive)",
    rarity: "Code Card",
    number: "None",
    price: 0.97,
  },
  {
    card: "Pikachu ex",
    rarity: "Double Rare",
    number: "063",
    price: 0.94,
  },
  {
    card: "Skeledirge ex",
    rarity: "Double Rare",
    number: "037",
    price: 0.94,
  },
  {
    card: "Wo-Chien ex",
    rarity: "Double Rare",
    number: "027",
    price: 0.92,
  },
  {
    card: "Noivern ex",
    rarity: "Double Rare",
    number: "153",
    price: 0.91,
  },
  {
    card: "Reversal Energy",
    rarity: "Uncommon",
    number: "192",
    price: 0.86,
  },
  {
    card: "Chi-Yu ex",
    rarity: "Double Rare",
    number: "040",
    price: 0.82,
  },
  {
    card: "Paldean Clodsire ex",
    rarity: "Double Rare",
    number: "130",
    price: 0.8,
  },
  {
    card: "Quaquaval ex",
    rarity: "Double Rare",
    number: "052",
    price: 0.76,
  },
  {
    card: "Bellibolt ex",
    rarity: "Double Rare",
    number: "079",
    price: 0.73,
  },
  {
    card: "Slowking ex",
    rarity: "Double Rare",
    number: "086",
    price: 0.72,
  },
  {
    card: "Lycanroc ex",
    rarity: "Double Rare",
    number: "117",
    price: 0.67,
  },
  {
    card: "Dedenne ex",
    rarity: "Double Rare",
    number: "093",
    price: 0.59,
  },
  {
    card: "Copperajah ex",
    rarity: "Double Rare",
    number: "150",
    price: 0.57,
  },
  {
    card: "Jet Energy",
    rarity: "Uncommon",
    number: "190",
    price: 0.54,
  },
  {
    card: "Code Card - Paldea Evolved Elite Trainer Box",
    rarity: "Code Card",
    number: "None",
    price: 0.4,
  },
  {
    card: "Bravery Charm",
    rarity: "Uncommon",
    number: "173",
    price: 0.38,
  },
  {
    card: "Superior Energy Retrieval",
    rarity: "Uncommon",
    number: "189",
    price: 0.38,
  },
  {
    card: "Artazon",
    rarity: "Uncommon",
    number: "171",
    price: 0.29,
  },
  {
    card: "Luminous Energy",
    rarity: "Uncommon",
    number: "191",
    price: 0.26,
  },
  {
    card: "Baxcalibur",
    rarity: "Rare",
    number: "060",
    price: 0.24,
  },
  {
    card: "Spiritomb",
    rarity: "Rare",
    number: "089",
    price: 0.23,
  },
  {
    card: "Luxray",
    rarity: "Rare",
    number: "071",
    price: 0.2,
  },
  {
    card: "Super Rod",
    rarity: "Common",
    number: "188",
    price: 0.2,
  },
  {
    card: "Boss's Orders",
    rarity: "Rare",
    number: "172",
    price: 0.19,
  },
  {
    card: "Therapeutic Energy",
    rarity: "Uncommon",
    number: "193",
    price: 0.19,
  },
  {
    card: "Frigibax",
    rarity: "Common",
    number: "057",
    price: 0.16,
  },
  {
    card: "Hydreigon",
    rarity: "Rare",
    number: "140",
    price: 0.15,
  },
  {
    card: "Mimikyu",
    rarity: "Rare",
    number: "097",
    price: 0.15,
  },
  {
    card: "Paldean Tauros",
    rarity: "Uncommon",
    number: "041",
    price: 0.14,
  },
  {
    card: "Wattrel",
    rarity: "Common",
    number: "080",
    price: 0.14,
  },
  {
    card: "Ceruledge",
    rarity: "Rare",
    number: "098",
    price: 0.13,
  },
  {
    card: "Gyarados",
    rarity: "Rare",
    number: "043",
    price: 0.13,
  },
  {
    card: "Tinkaton",
    rarity: "Rare",
    number: "105",
    price: 0.13,
  },
  {
    card: "Frigibax",
    rarity: "Common",
    number: "058",
    price: 0.12,
  },
  {
    card: "Paldean Tauros",
    rarity: "Uncommon",
    number: "108",
    price: 0.12,
  },
  {
    card: "Code Card - Paldea Evolved Booster Pack",
    rarity: "Code Card",
    number: "None",
    price: 0.11,
  },
  {
    card: "Raichu",
    rarity: "Uncommon",
    number: "064",
    price: 0.11,
  },
  {
    card: "Orthworm",
    rarity: "Rare",
    number: "151",
    price: 0.1,
  },
  {
    card: "Tyranitar",
    rarity: "Rare",
    number: "135",
    price: 0.1,
  },
  {
    card: "Fuecoco",
    rarity: "Common",
    number: "035",
    price: 0.09,
  },
  {
    card: "Paldean Wooper",
    rarity: "Common",
    number: "128",
    price: 0.09,
  },
  {
    card: "Paldean Wooper",
    rarity: "Common",
    number: "129",
    price: 0.09,
  },
  {
    card: "Pikachu",
    rarity: "Common",
    number: "062",
    price: 0.09,
  },
  {
    card: "Sprigatito",
    rarity: "Common",
    number: "013",
    price: 0.09,
  },
  {
    card: "Calamitous Snowy Mountain",
    rarity: "Uncommon",
    number: "174",
    price: 0.08,
  },
  {
    card: "Charcadet",
    rarity: "Common",
    number: "039",
    price: 0.08,
  },
  {
    card: "Choice Belt",
    rarity: "Uncommon",
    number: "176",
    price: 0.08,
  },
  {
    card: "Garganacl",
    rarity: "Rare",
    number: "123",
    price: 0.08,
  },
  {
    card: "Glimmora",
    rarity: "Rare",
    number: "126",
    price: 0.08,
  },
  {
    card: "Grafaiai",
    rarity: "Uncommon",
    number: "146",
    price: 0.08,
  },
  {
    card: "Oranguru",
    rarity: "Uncommon",
    number: "094",
    price: 0.08,
  },
  {
    card: "Paldean Tauros",
    rarity: "Uncommon",
    number: "028",
    price: 0.08,
  },
  {
    card: "Pyroar",
    rarity: "Uncommon",
    number: "032",
    price: 0.08,
  },
  {
    card: "Rabsca",
    rarity: "Rare",
    number: "099",
    price: 0.08,
  },
  {
    card: "Sprigatito",
    rarity: "Common",
    number: "012",
    price: 0.08,
  },
  {
    card: "Tinkatuff",
    rarity: "Uncommon",
    number: "103",
    price: 0.08,
  },
  {
    card: "Tinkatuff",
    rarity: "Uncommon",
    number: "104",
    price: 0.08,
  },
  {
    card: "Abomasnow",
    rarity: "Rare",
    number: "011",
    price: 0.07,
  },
  {
    card: "Arctibax",
    rarity: "Uncommon",
    number: "059",
    price: 0.07,
  },
  {
    card: "Calamitous Wasteland",
    rarity: "Uncommon",
    number: "175",
    price: 0.07,
  },
  {
    card: "Charcadet",
    rarity: "Common",
    number: "038",
    price: 0.07,
  },
  {
    card: "Floragato",
    rarity: "Uncommon",
    number: "014",
    price: 0.07,
  },
  {
    card: "Fuecoco",
    rarity: "Common",
    number: "034",
    price: 0.07,
  },
  {
    card: "Glimmet",
    rarity: "Common",
    number: "124",
    price: 0.07,
  },
  {
    card: "Lokix",
    rarity: "Rare",
    number: "021",
    price: 0.07,
  },
  {
    card: "Magikarp",
    rarity: "Common",
    number: "042",
    price: 0.07,
  },
  {
    card: "Noibat",
    rarity: "Common",
    number: "152",
    price: 0.07,
  },
  {
    card: "Oricorio",
    rarity: "Rare",
    number: "033",
    price: 0.07,
  },
  {
    card: "Practice Studio",
    rarity: "Uncommon",
    number: "186",
    price: 0.07,
  },
  {
    card: "Pupitar",
    rarity: "Uncommon",
    number: "111",
    price: 0.07,
  },
  {
    card: "Quaxly",
    rarity: "Common",
    number: "050",
    price: 0.07,
  },
  {
    card: "Sableye",
    rarity: "Rare",
    number: "136",
    price: 0.07,
  },
  {
    card: "Saguaro",
    rarity: "Uncommon",
    number: "187",
    price: 0.07,
  },
  {
    card: "Shroodle",
    rarity: "Common",
    number: "144",
    price: 0.07,
  },
  {
    card: "Tinkatink",
    rarity: "Common",
    number: "100",
    price: 0.07,
  },
  {
    card: "Tinkatink",
    rarity: "Common",
    number: "101",
    price: 0.07,
  },
  {
    card: "Veluza",
    rarity: "Rare",
    number: "056",
    price: 0.07,
  },
  {
    card: "Weavile",
    rarity: "Rare",
    number: "134",
    price: 0.07,
  },
  {
    card: "Wigglytuff",
    rarity: "Rare",
    number: "084",
    price: 0.07,
  },
  {
    card: "Azumarill",
    rarity: "Uncommon",
    number: "045",
    price: 0.06,
  },
  {
    card: "Brambleghast",
    rarity: "Uncommon",
    number: "024",
    price: 0.06,
  },
  {
    card: "Bramblin",
    rarity: "Common",
    number: "022",
    price: 0.06,
  },
  {
    card: "Bramblin",
    rarity: "Common",
    number: "023",
    price: 0.06,
  },
  {
    card: "Cetitan",
    rarity: "Uncommon",
    number: "055",
    price: 0.06,
  },
  {
    card: "Clavell",
    rarity: "Common",
    number: "177",
    price: 0.06,
  },
  {
    card: "Cufant",
    rarity: "Common",
    number: "149",
    price: 0.06,
  },
  {
    card: "Dudunsparce",
    rarity: "Uncommon",
    number: "157",
    price: 0.06,
  },
  {
    card: "Farigiraf",
    rarity: "Uncommon",
    number: "155",
    price: 0.06,
  },
  {
    card: "Flamigo",
    rarity: "Uncommon",
    number: "170",
    price: 0.06,
  },
  {
    card: "Giacomo",
    rarity: "Uncommon",
    number: "182",
    price: 0.06,
  },
  {
    card: "Hariyama",
    rarity: "Rare",
    number: "113",
    price: 0.06,
  },
  {
    card: "Jumpluff",
    rarity: "Rare",
    number: "003",
    price: 0.06,
  },
  {
    card: "Kilowattrel",
    rarity: "Uncommon",
    number: "082",
    price: 0.06,
  },
  {
    card: "Larvitar",
    rarity: "Common",
    number: "110",
    price: 0.06,
  },
  {
    card: "Murkrow",
    rarity: "Common",
    number: "131",
    price: 0.06,
  },
  {
    card: "Nacli",
    rarity: "Common",
    number: "121",
    price: 0.06,
  },
  {
    card: "Naclstack",
    rarity: "Uncommon",
    number: "122",
    price: 0.06,
  },
  {
    card: "Nymble",
    rarity: "Common",
    number: "019",
    price: 0.06,
  },
  {
    card: "Pawmot",
    rarity: "Rare",
    number: "076",
    price: 0.06,
  },
  {
    card: "Pelipper",
    rarity: "Uncommon",
    number: "159",
    price: 0.06,
  },
  {
    card: "Rellor",
    rarity: "Common",
    number: "026",
    price: 0.06,
  },
  {
    card: "Rockruff",
    rarity: "Common",
    number: "116",
    price: 0.06,
  },
  {
    card: "Shinx",
    rarity: "Common",
    number: "068",
    price: 0.06,
  },
  {
    card: "Shroodle",
    rarity: "Common",
    number: "145",
    price: 0.06,
  },
  {
    card: "Slaking",
    rarity: "Rare",
    number: "162",
    price: 0.06,
  },
  {
    card: "Slowpoke",
    rarity: "Common",
    number: "085",
    price: 0.06,
  },
  {
    card: "Spidops",
    rarity: "Uncommon",
    number: "018",
    price: 0.06,
  },
  {
    card: "Tandemaus",
    rarity: "Common",
    number: "166",
    price: 0.06,
  },
  {
    card: "Tinkatink",
    rarity: "Common",
    number: "102",
    price: 0.06,
  },
  {
    card: "Vespiquen",
    rarity: "Uncommon",
    number: "009",
    price: 0.06,
  },
  {
    card: "Wattrel",
    rarity: "Common",
    number: "081",
    price: 0.06,
  },
  {
    card: "Zweilous",
    rarity: "Uncommon",
    number: "139",
    price: 0.06,
  },
  {
    card: "Corviknight",
    rarity: "Uncommon",
    number: "148",
    price: 0.05,
  },
  {
    card: "Corvisquire",
    rarity: "Common",
    number: "165",
    price: 0.05,
  },
  {
    card: "Crocalor",
    rarity: "Uncommon",
    number: "036",
    price: 0.05,
  },
  {
    card: "Deino",
    rarity: "Common",
    number: "138",
    price: 0.05,
  },
  {
    card: "Falkner",
    rarity: "Uncommon",
    number: "180",
    price: 0.05,
  },
  {
    card: "Fighting Au Lait",
    rarity: "Uncommon",
    number: "181",
    price: 0.05,
  },
  {
    card: "Glimmet",
    rarity: "Common",
    number: "125",
    price: 0.05,
  },
  {
    card: "Honchkrow",
    rarity: "Uncommon",
    number: "132",
    price: 0.05,
  },
  {
    card: "Luxio",
    rarity: "Uncommon",
    number: "070",
    price: 0.05,
  },
  {
    card: "Maschiff",
    rarity: "Common",
    number: "142",
    price: 0.05,
  },
  {
    card: "Maushold",
    rarity: "Uncommon",
    number: "168",
    price: 0.05,
  },
  {
    card: "Nacli",
    rarity: "Common",
    number: "120",
    price: 0.05,
  },
  {
    card: "Nymble",
    rarity: "Common",
    number: "020",
    price: 0.05,
  },
  {
    card: "Pincurchin",
    rarity: "Common",
    number: "072",
    price: 0.05,
  },
  {
    card: "Quaxly",
    rarity: "Common",
    number: "049",
    price: 0.05,
  },
  {
    card: "Quaxwell",
    rarity: "Uncommon",
    number: "051",
    price: 0.05,
  },
  {
    card: "Rellor",
    rarity: "Common",
    number: "025",
    price: 0.05,
  },
  {
    card: "Seviper",
    rarity: "Uncommon",
    number: "137",
    price: 0.05,
  },
  {
    card: "Shinx",
    rarity: "Common",
    number: "069",
    price: 0.05,
  },
  {
    card: "Skiploom",
    rarity: "Uncommon",
    number: "002",
    price: 0.05,
  },
  {
    card: "Slakoth",
    rarity: "Common",
    number: "160",
    price: 0.05,
  },
  {
    card: "Tadbulb",
    rarity: "Common",
    number: "077",
    price: 0.05,
  },
  {
    card: "Tadbulb",
    rarity: "Common",
    number: "078",
    price: 0.05,
  },
  {
    card: "Talonflame",
    rarity: "Uncommon",
    number: "030",
    price: 0.05,
  },
  {
    card: "Tandemaus",
    rarity: "Common",
    number: "167",
    price: 0.05,
  },
  {
    card: "Wingull",
    rarity: "Common",
    number: "158",
    price: 0.05,
  },
  {
    card: "Cetoddle",
    rarity: "Common",
    number: "053",
    price: 0.04,
  },
  {
    card: "Cetoddle",
    rarity: "Common",
    number: "054",
    price: 0.04,
  },
  {
    card: "Croagunk",
    rarity: "Common",
    number: "114",
    price: 0.04,
  },
  {
    card: "Delivery Drone",
    rarity: "Uncommon",
    number: "178",
    price: 0.04,
  },
  {
    card: "Dendra",
    rarity: "Uncommon",
    number: "179",
    price: 0.04,
  },
  {
    card: "Eiscue",
    rarity: "Uncommon",
    number: "048",
    price: 0.04,
  },
  {
    card: "Falinks",
    rarity: "Common",
    number: "119",
    price: 0.04,
  },
  {
    card: "Gothitelle",
    rarity: "Uncommon",
    number: "092",
    price: 0.04,
  },
  {
    card: "Great Ball",
    rarity: "Common",
    number: "183",
    price: 0.04,
  },
  {
    card: "Grusha",
    rarity: "Uncommon",
    number: "184",
    price: 0.04,
  },
  {
    card: "Jigglypuff",
    rarity: "Common",
    number: "083",
    price: 0.04,
  },
  {
    card: "Litleo",
    rarity: "Common",
    number: "031\/293",
    price: 0.04,
  },
  {
    card: "Mabosstiff",
    rarity: "Uncommon",
    number: "143",
    price: 0.04,
  },
  {
    card: "Makuhita",
    rarity: "Common",
    number: "112",
    price: 0.04,
  },
  {
    card: "Mankey",
    rarity: "Common",
    number: "106",
    price: 0.04,
  },
  {
    card: "Marill",
    rarity: "Common",
    number: "044",
    price: 0.04,
  },
  {
    card: "Maschiff",
    rarity: "Common",
    number: "141",
    price: 0.04,
  },
  {
    card: "Mismagius",
    rarity: "Uncommon",
    number: "088",
    price: 0.04,
  },
  {
    card: "Palossand",
    rarity: "Uncommon",
    number: "096",
    price: 0.04,
  },
  {
    card: "Pawmi",
    rarity: "Common",
    number: "074",
    price: 0.04,
  },
  {
    card: "Pawmo",
    rarity: "Uncommon",
    number: "075",
    price: 0.04,
  },
  {
    card: "Pincurchin",
    rarity: "Uncommon",
    number: "073",
    price: 0.04,
  },
  {
    card: "Pineco",
    rarity: "Common",
    number: "004",
    price: 0.04,
  },
  {
    card: "Primeape",
    rarity: "Uncommon",
    number: "107",
    price: 0.04,
  },
  {
    card: "Rookidee",
    rarity: "Common",
    number: "164",
    price: 0.04,
  },
  {
    card: "Sandygast",
    rarity: "Common",
    number: "095",
    price: 0.04,
  },
  {
    card: "Sudowoodo",
    rarity: "Uncommon",
    number: "109",
    price: 0.04,
  },
  {
    card: "Tarountula",
    rarity: "Common",
    number: "016",
    price: 0.04,
  },
  {
    card: "Tarountula",
    rarity: "Common",
    number: "017",
    price: 0.04,
  },
  {
    card: "Toxicroak",
    rarity: "Uncommon",
    number: "115",
    price: 0.04,
  },
  {
    card: "Tropius",
    rarity: "Common",
    number: "007",
    price: 0.04,
  },
  {
    card: "Vigoroth",
    rarity: "Common",
    number: "161",
    price: 0.04,
  },
  {
    card: "Bombirdier",
    rarity: "Uncommon",
    number: "147",
    price: 0.03,
  },
  {
    card: "Combee",
    rarity: "Common",
    number: "008",
    price: 0.03,
  },
  {
    card: "Delibird",
    rarity: "Common",
    number: "046",
    price: 0.03,
  },
  {
    card: "Dunsparce",
    rarity: "Common",
    number: "156",
    price: 0.03,
  },
  {
    card: "Electrode",
    rarity: "Uncommon",
    number: "067",
    price: 0.03,
  },
  {
    card: "Fletchinder",
    rarity: "Uncommon",
    number: "029",
    price: 0.03,
  },
  {
    card: "Fletchling",
    rarity: "Common",
    number: "163",
    price: 0.03,
  },
  {
    card: "Girafarig",
    rarity: "Common",
    number: "154",
    price: 0.03,
  },
  {
    card: "Gothita",
    rarity: "Common",
    number: "090",
    price: 0.03,
  },
  {
    card: "Gothorita",
    rarity: "Common",
    number: "091",
    price: 0.03,
  },
  {
    card: "Heracross",
    rarity: "Uncommon",
    number: "006",
    price: 0.03,
  },
  {
    card: "Hoppip",
    rarity: "Common",
    number: "001",
    price: 0.03,
  },
  {
    card: "Magnemite",
    rarity: "Common",
    number: "065",
    price: 0.03,
  },
  {
    card: "Misdreavus",
    rarity: "Common",
    number: "087",
    price: 0.03,
  },
  {
    card: "Passimian",
    rarity: "Uncommon",
    number: "118",
    price: 0.03,
  },
  {
    card: "Sneasel",
    rarity: "Common",
    number: "133",
    price: 0.03,
  },
  {
    card: "Snover",
    rarity: "Common",
    number: "010",
    price: 0.03,
  },
  {
    card: "Voltorb",
    rarity: "Common",
    number: "066",
    price: 0.03,
  },
  {
    card: "Luvdisc",
    rarity: "Common",
    number: "047",
    price: 0.02,
  },
]);

const pullRates = {
  "Special Illustration Rare": 0.0317, // 5%
  "Illustration Rare": 0.077, // 10%
  "Ultra Rare": 0.0664,
  "Hyper Rare": 0.0176,
  "Double Rare": 0.1372,
  Rare: 0.7964,
  Uncommon: 3,
  Common: 4,
  "Reverse Holo": 1.8737,
};

const rarityValues = cards.value.reduce((acc, item) => {
  if (item.rarity !== "Code Card") {
    if (!acc[item.rarity]) {
      acc[item.rarity] = { totalValue: 0, count: 0 };
    }
    acc[item.rarity].totalValue += item.price;
    acc[item.rarity].count++;

    if (["Rare", "Common", "Uncommon"].includes(item.rarity)) {
      if (!acc["Reverse Holo"]) {
        acc["Reverse Holo"] = { totalValue: 0, count: 0 };
      }
      acc["Reverse Holo"].totalValue += item.price;
      acc["Reverse Holo"].count++;
    }
  }
  return acc;
}, {});

const result = Object.keys(rarityValues).map((key) => ({
  rarity: key,
  totalValue: rarityValues[key].totalValue,
  count: rarityValues[key].count,
  averageValue: rarityValues[key].totalValue / rarityValues[key].count,
  pullRate: pullRates[key] || "Not defined",
}));
</script>
